#!/usr/bin/env node
/**
 * Inlines every SVG exported from Figma (src/assets/icons/*.svg) into a typed
 * TS module so react-native-svg's <SvgXml> can render the exact exported bytes
 * on both platforms — no Metro transformer or extra native config required.
 *
 * The .svg files remain the source of truth. Re-run after re-exporting:
 *   npm run icons
 */
const fs = require('fs');
const path = require('path');

const ICON_DIR = path.join(__dirname, '..', 'src', 'assets', 'icons');
const OUT_FILE = path.join(ICON_DIR, 'index.ts');

const toCamel = name =>
  name.replace(/[-_](\w)/g, (_, c) => c.toUpperCase());

const files = fs
  .readdirSync(ICON_DIR)
  .filter(f => f.endsWith('.svg'))
  .sort();

if (files.length === 0) {
  console.error(`No .svg files found in ${ICON_DIR}`);
  process.exit(1);
}

const entries = files.map(file => {
  const xml = fs.readFileSync(path.join(ICON_DIR, file), 'utf8').trim();
  // The width attribute on the root <svg> is the leaf size the designer drew.
  const match = xml.match(/<svg[^>]*\swidth="([\d.]+)"/);
  const size = match ? Math.round(parseFloat(match[1]) * 1000) / 1000 : 24;
  const key = toCamel(path.basename(file, '.svg'));
  const escaped = xml.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  return `  ${key}: {\n    size: ${size},\n    xml: \`${escaped}\`,\n  },`;
});

const out = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-icons.js — do not edit by hand.
 * Source: src/assets/icons/*.svg (exported from Figma "Betting App").
 * Regenerate with: npm run icons
 */
export const icons = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof icons;
`;

fs.writeFileSync(OUT_FILE, out, 'utf8');
console.log(
  `Wrote ${files.length} icons to ${path.relative(process.cwd(), OUT_FILE)}`,
);
